import test from 'node:test';
import assert from 'node:assert/strict';
import {coalitionFixture} from './coalition-fixture.mjs';
import {buildingPanelMarkup} from '../client/buildings/building-panel-controller.js';
function fixture(){const f=coalitionFixture();f.a.gold=100000;for(const id of ['a','b'])f.s.world.territories[id].buildings.push({id:'airport-'+id,type:'airport',level:1,status:'active'});f.s.save();return f;}
function args(f,extra={}){const body={kind:'expedition',unitId:'expedition',territoryId:'b',requestId:'airport-test-001',...extra};return {...body,goldCost:f.s.airports.quote(f.a,body).goldCost};}
test('airport construction is listed on vacant territory, unlimited across territories and single level',()=>{const f=coalitionFixture();f.a.gold=100000;const c=f.s.world.territories.c;c.ownerId='a';c.capitalOf=null;f.s.world.players.a.territoryIds.push('c');f.s.save();let view=f.s.buildings.territoryView(f.a,f.s.world,'c');assert.ok(view.availableTypes.includes('airport'));assert.match(buildingPanelMarkup({view,catalog:f.s.buildings.catalog(),walletGold:f.a.gold}),/data-build-type="airport"/);for(const id of ['a','c']){const r=f.s.buildings.build(f.a,f.s.world,id,'airport','gold');assert.equal(r.building.status,'active');assert.equal(r.building.maxLevel,1);assert.match(r.building.name,/a机场/);}assert.equal(f.a.gold,64000);assert.throws(()=>f.s.buildings.build(f.a,f.s.world,'c','airport','gold'));});
test('allied air transport debits gold once, no oil, arrives in 60 seconds and survives reload',()=>{const f=fixture(),body=args(f),gold=f.a.gold,oil=f.a.oil.balance;f.s.airports.move(f.a,body);assert.equal(f.a.gold,gold-body.goldCost);assert.equal(f.a.oil.balance,oil);f.s.airports.move(f.a,body);assert.equal(f.a.gold,gold-body.goldCost);f.tick(59000);f.s.save();assert.equal(f.a.expeditionPiece.territoryId,'a');f.reload();f.tick(1000);f.s.save();assert.equal(f.a.expeditionPiece.territoryId,'b');assert.equal(f.a.expeditionPiece.movement,null);});
test('requires both usable completed airports and rejects enemies, suppressed or missing endpoints',()=>{const f=fixture();assert.throws(()=>f.s.airports.quote(f.a,{kind:'expedition',unitId:'expedition',territoryId:'c'}),/起点/);f.s.world.territories.b.raidSuppression={until:f.now+100000};assert.throws(()=>args(f),/起点/);delete f.s.world.territories.b.raidSuppression;f.s.world.territories.b.buildings[0].status='constructing';assert.throws(()=>args(f),/起点/);});
test('destination demolished in flight refunds exactly and returns to origin',()=>{const f=fixture(),body=args(f);f.s.airports.move(f.a,body);const gold=f.a.gold;f.s.world.territories.b.buildings=[];f.tick(60000);f.s.save();assert.equal(f.a.expeditionPiece.territoryId,'a');assert.equal(f.a.expeditionPiece.movement,null);assert.equal(f.a.goldLedger.filter(e=>e.reason==='airport-flight-refund').reduce((sum,e)=>sum+e.delta,0),body.goldCost);const after=f.a.gold;f.s.save();assert.equal(f.a.gold,after);});
test('failed persistence rolls back ticket and movement',()=>{const f=fixture(),body=args(f),gold=f.a.gold,save=f.s.repository.save;let calls=0;f.s.repository.save=v=>{if(++calls===2)throw Error('disk failed');return save(v);};assert.throws(()=>f.s.airports.move(f.a,body),/disk failed/);assert.equal(f.a.gold,gold);assert.equal(f.a.expeditionPiece.movement,null);assert.equal(f.a.airportRequests?.[body.requestId],undefined);});
test('scouts use same flight timeline and cannot dig while airborne',()=>{const f=fixture();f.a.scouting??={tasks:[],units:{}};f.a.scouting.units={s:{id:'s',name:'测试球探',territoryId:'a',movement:null}};const body=args(f,{kind:'scout',unitId:'s'});f.s.airports.move(f.a,body);assert.throws(()=>f.s.scouting.requireIdle(f.a,f.a.scouting.units.s),/移动/);f.tick(60000);f.s.save();assert.equal(f.a.scouting.units.s.territoryId,'b');});
test('coalition commander pays ticket and members oil remains unchanged',()=>{const f=fixture();f.s.coalitions.mutate(f.a,{action:'create',requestId:'create-test-001'});const army=f.s.coalitions.find(f.a),body=args(f,{kind:'coalition',unitId:army.id}),gold=f.a.gold,oil=[f.a.oil.balance,f.b.oil.balance];f.s.airports.move(f.a,body);assert.equal(f.a.gold,gold-body.goldCost);assert.deepEqual([f.a.oil.balance,f.b.oil.balance],oil);f.tick(60000);f.s.save();assert.equal(army.territoryId,'b');assert.equal(army.movement,null);});
