import test from 'node:test';import assert from 'node:assert/strict';import {coalitionFixture} from './coalition-fixture.mjs';import {coalitionAttackEntries,defenceEntries} from '../client/challenge/defence-notifications.js';
test('dismissed reports persist per account while history remains readable',()=>{const f=coalitionFixture(),b={id:'battle',challengeId:'battle',coalitionId:'army',coalitionContributors:['a','b'],attackerId:'a',defenderId:'c'};f.a.battleHistory=[structuredClone(b)];f.b.battleHistory=[structuredClone(b)];f.s.save();f.s.dismissBattleReport(f.a,'battle');assert.equal(coalitionAttackEntries(f.s.state(f.a)).history.length,0);assert.equal(coalitionAttackEntries(f.s.state(f.b)).history.length,1);assert.equal(f.s.challenges.status(f.a,'battle').completed,true);f.reload();assert.deepEqual(f.a.battleReportReadIds,['battle']);f.s.dismissBattleReport(f.a,'battle');assert.deepEqual(f.a.battleReportReadIds,['battle']);});
test('invalid or other account reports rejected and failed persistence rolls back',()=>{const f=coalitionFixture();f.a.battleHistory=[{id:'own',defenderId:'a'}];assert.throws(()=>f.s.dismissBattleReport(f.b,'own'),/无权/);assert.throws(()=>f.s.dismissBattleReport(f.a,'live'),/不存在/);f.fail(true);assert.throws(()=>f.s.dismissBattleReport(f.a,'own'),/disk failure/);assert.equal(f.a.battleReportReadIds,undefined);f.fail(false);f.s.dismissBattleReport(f.a,'own');assert.equal(defenceEntries(f.s.state(f.a)).history.length,0);});
test('read filter leaves ongoing matches and new reports visible',()=>{const state={playerId:'a',battleReportReadIds:['old'],world:{activeChallenges:{x:{id:'old',coalitionId:'army',coalitionContributors:['a']}}},battleHistory:[{id:'old',coalitionId:'army',coalitionContributors:['a']},{id:'new',coalitionId:'army',coalitionContributors:['a']}]};assert.equal(coalitionAttackEntries(state).active.length,1);assert.deepEqual(coalitionAttackEntries(state).history.map(b=>b.id),['new']);});

test('bond notices acknowledge all variants without modifying gold, ledger or receipt; isolated and durable',()=>{
 const f=coalitionFixture();f.a.pvpNotices=['held','win','loss','cancel','defence'].map(id=>({id,text:id,createdAt:f.now}));f.b.pvpNotices=[{id:'held',text:'other',createdAt:f.now}];f.s.save();const gold=f.a.gold,ledger=structuredClone(f.a.goldLedger);
 for(const id of ['held','win','loss','cancel','defence'])f.s.dismissPvpNotice(f.a,id);
 assert.equal(f.a.gold,gold);assert.deepEqual(f.a.goldLedger,ledger);assert.equal(f.a.pvpNotices.length,5);assert.equal(f.b.pvpNoticeReadIds,undefined);f.reload();assert.equal(f.s.state(f.a).pvpNoticeReadIds.length,5);f.s.dismissPvpNotice(f.a,'held');assert.equal(f.a.pvpNoticeReadIds.length,5);
 assert.throws(()=>f.s.dismissPvpNotice(f.b,'defence'),/无权/);
});
test('failed bond acknowledgement rolls back and new notices remain unread',()=>{const f=coalitionFixture();f.a.pvpNotices=[{id:'held'}];f.fail(true);assert.throws(()=>f.s.dismissPvpNotice(f.a,'held'),/disk failure/);assert.equal(f.a.pvpNoticeReadIds,undefined);f.fail(false);f.s.dismissPvpNotice(f.a,'held');f.a.pvpNotices.push({id:'refunded'});assert.deepEqual(f.a.pvpNoticeReadIds,['held']);});
