import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {readFileSync} from 'node:fs';
import {ExpeditionFitnessService,activeExpeditionPlayerIds} from '../server/application/expedition-fitness-service.mjs';
import {setAbsence,absenceMatches} from '../shared/football/match-availability.mjs';
import {loadCampaignMapData} from '../client/map/campaign-map-data.js';
import {EliteChallengeService} from '../server/application/elite-challenge-service.mjs';
import {EconomyService} from '../server/application/economy-service.mjs';
import {EnhancementService} from '../server/application/enhancement-service.mjs';
import {hydrateCampaignWorld} from '../server/infrastructure/campaign-save-migrations.mjs';
import {ELITE_CLUBS,eliteFanReward,applyEliteTerritoryRules,canonicalClubName} from '../shared/config/elite-clubs.mjs';
import {strongestEliteLineup} from '../shared/football/elite-lineup.mjs';
import {inferElevenBoardRoles} from '../formation-rules.js';
import {createTerritoryWorld,canAttack,canAttackFromTerritory,captureTerritory} from '../territory-model.js';
import {conquestAttackBlock,conquestState} from '../shared/config/conquest.mjs';
import {eliteWindowMarkup} from '../client/elite/elite-controller.js';
const read=f=>JSON.parse(readFileSync(new URL('../'+f,import.meta.url)));
const catalog=read('assets/data/s4-player-catalog.json'),rawIndex=read('assets/data/territory-index.json');
function fixture(){let at=1800000000000,broken=false;const territoryIndex=structuredClone(rawIndex),world=createTerritoryWorld(territoryIndex),economy=new EconomyService({now:()=>at}),enhancement=new EnhancementService({economy});
 const c={world,territoryIndex,playerDatabase:catalog,economy,enhancement,now:()=>at,random:()=>.2,save(){if(broken)throw Error('disk failure');},accounts:new Map(),campaignWeather:()=>null};
 const elite=new EliteChallengeService({campaign:c});
 function account(id='a'){const chosen=[];for(const role of ['GK','LB','RB','CB','CB','DM','AM','LM','RM','ST','ST'])chosen.push(catalog.find(p=>p.role===role&&!p.isX&&!chosen.some(v=>v.id===p.id)));const roster=structuredClone(chosen);for(const p of roster)p.state={fitness:23};
 const a={id,setupComplete:true,gold:100000,goldLedger:[],draft:{roster,teamName:id},playerSquads:{schemaVersion:2,assignments:Object.fromEntries(roster.map(p=>[p.id,'expedition']))},tactics:{squads:{expedition:{starters:roster.map(p=>p.id)}}},resources:{fans:200}};c.accounts.set(id,a);return a;}
 return {c,elite,account,setTime:n=>at=n,setBroken:v=>broken=v};
}
const request=(clubId='real-madrid')=>({clubId,requestId:crypto.randomUUID()});
function finish(f,a,won){const ch=f.elite.active(a);ch.leg.match.finished=true;ch.leg.match.score=won?[0,1]:[1,0];ch.leg.winnerIndex=won?1:0;f.elite.settle(a);}
test('only 18 eligible clubs remain on 13 territories; other club land becomes ordinary',()=>{const index=structuredClone(rawIndex),before=index.territories.filter(t=>t.initialOwner.type==='club').length;applyEliteTerritoryRules(index);const kept=index.territories.filter(t=>t.initialOwner.type==='club');assert.equal(kept.length,13);assert.equal(new Set(kept.flatMap(t=>t.clubIds)).size,18);assert.equal(before-kept.length,25);for(const t of index.territories.filter(t=>t.historicalClubIds?.length&&!t.clubIds.length)){assert.equal(t.initialOwner.type,'neutral');assert.equal(t.spawnAllowed,Boolean(t.playable));}assert.deepEqual(index.territories.map(t=>t.landNeighbors),rawIndex.territories.map(t=>t.landNeighbors));const again=structuredClone(index);applyEliteTerritoryRules(index);assert.deepEqual(index,again);});
test('all 18 teams use their own strongest legal eleven, +5 real attributes and matching engine roles',()=>{const f=fixture();for(const club of ELITE_CLUBS){const t=f.elite.team(club.id),roles=inferElevenBoardRoles(t.seat.players.map(p=>({id:p.id,position:t.seat.positions[p.id]})),t.seat.formationLines);assert.equal(t.seat.players.length,11,club.name);assert.equal(new Set(t.seat.players.map(p=>p.sourceName||p.name)).size,11);for(const [i,p] of t.seat.players.entries()){assert.equal(p.club,club.name);assert.equal(p.upgradeLevel,5);assert.equal(p.state.fitness,100);assert.equal(roles[p.id],t.preview[i].role,club.name+' '+p.name);const source=t.sources.find(s=>s.id===p.cardDefinitionId);assert.ok(source);assert.equal(canonicalClubName(source.club),club.name);assert.ok([source.role,source.secondaryRole].includes(roles[p.id]));assert.equal(p.overall,source.overall+7);for(const key of Object.keys(source.attributes))assert.equal(p.attributes[key],Math.min(99,source.attributes[key]+7));}assert.equal(t.seat.style,club.style);assert.equal(t.seat.tacticalPlans.opening.tacticalDimensions.pressing,club.tacticalDimensions.pressing);}});
test('optimizer prefers a stronger legal secondary position and updates after catalog changes',()=>{const f=fixture(),t=f.elite.team('real-madrid'),players=t.preview.map((v,i)=>({id:'p'+i,name:'p'+i,role:v.role,overall:50}));players.push({id:'strong',role:'AM',secondaryRole:'ST',overall:90});const result=strongestEliteLineup(players,'4-4-2');assert.ok(result.some(e=>e.player.id==='strong'));assert.equal(result.reduce((s,e)=>s+e.player.overall,0),590);f.c.playerDatabase=structuredClone(catalog);f.c.playerDatabase.find(p=>p.id===t.sources[0].id).overall+=1;assert.notEqual(f.elite.team('real-madrid'),t);});
test('elite land blocks land attacks, maritime permission bypass and direct capture',()=>{const f=fixture(),target=f.c.territoryIndex.territories.find(t=>t.eliteClubIds?.length).territoryId,source=f.c.territoryIndex.territories.find(t=>!t.eliteClubIds?.length).territoryId;f.c.world.players.a={territoryIds:[source]};assert.equal(canAttack(f.c.territoryIndex,f.c.world,'a',target).reason,'elite-challenge-only');assert.equal(canAttackFromTerritory(f.c.territoryIndex,f.c.world,'a',source,target).allowed,false);assert.throws(()=>captureTerritory(f.c.territoryIndex,f.c.world,'a',target,{permission:{allowed:true}}),/不能占领/);});
test('migration downgrades old neutral clubs, preserves shared stock and owned ordinary land',()=>{const f=fixture(),saved=structuredClone(f.c.world),demoted=f.c.territoryIndex.territories.find(t=>t.historicalClubIds?.length&&!t.eliteClubIds.length),owned=f.c.territoryIndex.territories.find(t=>!t.eliteClubIds?.length&&t!==demoted);saved.territories[demoted.territoryId].ownerType='club';saved.territories[demoted.territoryId].ownerId='old-club';Object.assign(saved.territories[owned.territoryId],{ownerType:'player',ownerId:'a'});saved.shop={rotationId:'kept'};const migrated=hydrateCampaignWorld(structuredClone(rawIndex),saved);assert.equal(migrated.territories[demoted.territoryId].ownerType,'neutral');assert.equal(migrated.territories[owned.territoryId].ownerId,'a');assert.deepEqual(migrated.shop,saved.shop);});
test('remote challenge spends 5000 once; full-fitness match copy preserves overworld roster',()=>{const f=fixture(),a=f.account(),r=request(),before=structuredClone(a.draft.roster),result=f.elite.begin(a,r);assert.deepEqual(f.elite.begin(a,r),result);assert.equal(a.gold,95000);assert.equal(a.goldLedger.length,1);assert.deepEqual(a.draft.roster,before);const ch=f.elite.active(a);assert.ok(ch.leg.away.players.every(p=>p.state.fitness===100));assert.equal(ch.leg.knockout,true);assert.equal(ch.leg.aggregateBaseScore,null);assert.throws(()=>f.elite.begin(a,request()),/已有/);assert.throws(()=>f.elite.begin(a,{...r,clubId:'barcelona'}),/不一致/);assert.throws(()=>f.elite.snapshot(f.account('b'),result.challengeId),/不属于/);});
test('failed validation and save errors never debit or leave a running challenge',()=>{const f=fixture(),a=f.account(),r=request();a.gold=4999;const before=structuredClone(a);assert.throws(()=>f.elite.begin(a,r),/金币不足/);assert.deepEqual(a,before);assert.equal(f.elite.active(a),null);a.gold=100000;f.setBroken(true);assert.throws(()=>f.elite.begin(a,r),/disk/);assert.equal(a.gold,100000);assert.equal(a.elite,undefined);assert.equal(f.elite.active(a),null);});
test('wins grant the 2000-fan top tier plus one persistent three-choice base-card reward',()=>{const f=fixture(),a=f.account(),r=request();f.elite.begin(a,r);finish(f,a,true);assert.equal(a.resources.fans,2200);assert.equal(a.elite.lastBattle.captured,false);assert.equal(a.elite.lastBattle.broadcasts.length,1);assert.deepEqual(a.elite.lastBattle.score,[1,0]);assert.equal(a.elite.reward.cards.length,3);assert.equal(new Set(a.elite.reward.cards.map(p=>p.id)).size,3);assert.ok(a.elite.reward.cards.every(p=>canonicalClubName(p.club)==='皇家马德里'&&p.upgradeLevel===0));assert.equal(f.elite.settle(a),false);assert.equal(a.resources.fans,2200);assert.throws(()=>f.elite.begin(a,request()),/领取/);const reward=a.elite.reward,body={rewardId:reward.id,playerId:reward.cards[0].id},chosen=f.elite.claim(a,body);assert.deepEqual(f.elite.claim(a,body),chosen);assert.equal(a.draft.roster.length,12);assert.equal(a.draft.roster.at(-1).upgradeLevel,0);assert.equal(a.draft.roster.at(-1).cardInstanceId,chosen.playerId);assert.equal(a.playerSquads.assignments[chosen.playerId],'garrison');assert.throws(()=>f.elite.claim(a,{...body,playerId:reward.cards[1].id}),/已领取/);assert.equal(f.elite.view(a).reward,null);});
test('loss imposes shared 20-minute expedition cooldown without consuming ordinary quota',()=>{const f=fixture(),a=f.account();f.elite.begin(a,request());finish(f,a,false);assert.equal(a.resources.fans,200);assert.equal(a.elite.reward,undefined);assert.equal(a.conquest.cooldownUntil,f.c.now()+20*60000);assert.equal(conquestState(a,f.c.now()).used,0);assert.ok(conquestAttackBlock(conquestState(a,f.c.now()),'neutral'));assert.throws(()=>f.elite.begin(a,request()),/休整|冷却/);f.setTime(a.conquest.cooldownUntil);assert.equal(f.elite.block(a),null);});
test('reward and victory persistence errors roll back and allow exactly one retry',()=>{const f=fixture(),a=f.account();f.elite.begin(a,request());f.setBroken(true);assert.throws(()=>finish(f,a,true),/disk/);assert.equal(a.resources.fans,200);assert.ok(f.elite.active(a));f.setBroken(false);f.elite.settle(a);assert.equal(a.resources.fans,2200);const r={rewardId:a.elite.reward.id,playerId:a.elite.reward.cards[0].id};f.setBroken(true);assert.throws(()=>f.elite.claim(a,r),/disk/);assert.equal(a.draft.roster.length,11);assert.equal(a.elite.reward.claimedId,null);f.setBroken(false);f.elite.claim(a,r);assert.equal(a.draft.roster.length,12);});
test('simultaneous accounts can challenge the same club and restart resumes deterministic engine',()=>{const f=fixture(),a=f.account(),b=f.account('b');f.elite.begin(a,request());f.elite.begin(b,request());f.setTime(f.c.now()+10000);f.elite.advance(f.c.now(),{maximumMatches:2,maximumChainsPerMatch:30});const saved=JSON.parse(JSON.stringify(f.c.world));f.c.world=saved;const restored=new EliteChallengeService({campaign:f.c});assert.equal(Object.keys(saved.eliteChallenges).length,2);assert.equal(typeof restored.active(a).leg.match.rng,'function');f.setTime(f.c.now()+200000);restored.advance(f.c.now(),{maximumMatches:2,maximumChainsPerMatch:300});assert.equal(Object.keys(saved.eliteChallenges).length,0);assert.ok(['win','loss'].includes(a.elite.lastBattle.outcome));assert.ok(['win','loss'].includes(b.elite.lastBattle.outcome));assert.equal(a.gold,95000);assert.equal(b.gold,95000);});
test('tied knockout match produces a penalty winner, never a draw reward',()=>{const f=fixture(),a=f.account();f.elite.begin(a,request());const leg=f.elite.active(a).leg;leg.match.score=[0,0];leg.match.finished=true;leg.extraTimePlayed=true;f.elite.settle(a);assert.ok(a.elite.lastBattle.penalties);assert.notEqual(...a.elite.lastBattle.penalties);assert.ok(['win','loss'].includes(a.elite.lastBattle.outcome));});
test('preview lists 18 clubs and eleven +5 cards; rewards open the shared three-choice flow',()=>{const f=fixture(),a=f.account();let html=eliteWindowMarkup(f.elite.view(a));assert.equal((html.match(/data-elite-club=/g)||[]).length,18);assert.equal((html.match(/class="elite-player"/g)||[]).length,0);assert.equal((html.match(/data-elite-tier=/g)||[]).length,5);assert.equal((html.match(/class="elite-badge /g)||[]).length,18);assert.doesNotMatch(html,/data-elite-begin=/);const detail=eliteWindowMarkup(f.elite.view(a),{page:'detail'});assert.equal((detail.match(/class="elite-player"/g)||[]).length,11);assert.doesNotMatch(detail,/data-elite-club=/);assert.match(detail,/data-elite-back/);assert.match(detail,/强化加5/);f.elite.begin(a,request());finish(f,a,true);html=eliteWindowMarkup(f.elite.view(a));assert.equal((html.match(/data-elite-reward/g)||[]).length,1);assert.doesNotMatch(html,/data-elite-claim=/);assert.equal(f.elite.view(a).reward.cards.length,3);assert.match(html,/2000 球迷/);});

test('map loader shows only eligible city clubs and downgrades matching feature metadata',async()=>{const data=await loadCampaignMapData({fetchImpl:async url=>({ok:true,json:async()=>read(url.replace('./','').split('?')[0])})});assert.equal(data.clubs.length,18);assert.equal(data.territoryIndex.territories.filter(t=>t.eliteClubIds?.length).length,13);assert.equal(data.territories.features.filter(f=>f.properties.initialOwnerType==='club').length,13);});
test('elite participants lock while live; real remaining fitness and per-match absences persist once',()=>{const f=fixture(),a=f.account();f.c.fitness=new ExpeditionFitnessService({world:f.c.world,accounts:f.c.accounts,now:f.c.now});const roster=a.draft.roster,absent=roster.find(p=>p.role==='ST');setAbsence(absent,'injury',1,{sourceLegId:'old'});f.elite.begin(a,request());const ch=f.elite.active(a),team=ch.leg.match.teams.find(t=>t.id===a.id),playing=team.players.find(p=>p.active!==false);assert.ok(activeExpeditionPlayerIds(f.c.world,a.id).has(playing.id));assert.ok(f.c.fitness.plans(a,f.c.now())[playing.id].stopAt!==null);playing.state.fitness=42;ch.leg.match.postMatchConsequences={injuries:[{teamIndex:1,playerId:playing.id,matches:2,reason:'lightning'}],suspensions:[]};finish(f,a,true);assert.equal(a.draft.roster.find(p=>p.id===playing.id).state.fitness,42);assert.equal(absenceMatches(a.draft.roster.find(p=>p.id===playing.id),'injury'),2);assert.equal(absenceMatches(absent,'injury'),0);assert.equal(activeExpeditionPlayerIds(f.c.world,a.id).size,0);assert.equal(f.elite.settle(a),false);assert.equal(absenceMatches(a.draft.roster.find(p=>p.id===playing.id),'injury'),2);});

test('fan rewards follow strength tiers and displayed values for all 18 clubs',()=>{const f=fixture(),a=f.account();assert.deepEqual([89.3,91.9,92,94.9,95,96.9,97,98.9,99,100].map(eliteFanReward),[600,600,900,900,1200,1200,1600,1600,2000,2000]);const v=f.elite.view(a);assert.deepEqual(Object.fromEntries([600,900,1200,1600,2000].map(n=>[n,v.clubs.filter(c=>c.fans===n).length])),{600:2,900:4,1200:5,1600:6,2000:1});for(const club of v.clubs){const selected=f.elite.view(a,club.id);assert.equal(selected.rules.fans,club.fans);assert.match(eliteWindowMarkup(selected,{page:'detail'}),new RegExp('胜利：'+club.fans+' 球迷'));}});
test('a lower-tier victory pays its previewed reward and locks it across catalog edits and restart',()=>{const f=fixture(),a=f.account();f.elite.begin(a,request('tottenham-hotspur'));assert.equal(f.elite.active(a).fanReward,600);f.c.world=JSON.parse(JSON.stringify(f.c.world));f.elite=new EliteChallengeService({campaign:f.c});f.c.playerDatabase=structuredClone(catalog);for(const p of f.c.playerDatabase)if(p.club==='托特纳姆热刺'){p.overall+=15;p.baseOverall+=15;}assert.equal(f.elite.view(a,'tottenham-hotspur').selected.fans,2000);assert.equal(f.elite.view(a).active.fanReward,600);finish(f,a,true);assert.equal(a.resources.fans,800);assert.equal(a.elite.lastBattle.rewards.fans,600);assert.equal(f.elite.settle(a),false);assert.equal(a.resources.fans,800);});
test('legacy in-progress matches keep the originally promised 1000 fans',()=>{const f=fixture(),a=f.account();f.elite.begin(a,request());delete f.elite.active(a).fanReward;assert.equal(f.elite.view(a).active.fanReward,1000);finish(f,a,true);assert.equal(a.resources.fans,1200);assert.equal(a.elite.lastBattle.rewards.fans,1000);});


test('curfew blocks new elite challenges without fees, while existing matches may finish',()=>{
 const f=fixture(),a=f.account(),midnight=Date.parse('2026-09-18T16:00:00Z');f.setTime(midnight);
 const balance=a.gold;assert.throws(()=>f.elite.begin(a,request()),/宵禁/);assert.equal(a.gold,balance);assert.equal(f.elite.active(a),null);
 f.setTime(midnight-60000);f.elite.begin(a,request());f.setTime(midnight+60000);finish(f,a,true);assert.ok(a.elite.lastBattle);
 const b=f.account('b');f.setTime(midnight+8*3600000);assert.doesNotThrow(()=>f.elite.begin(b,request()));
});
