import test from 'node:test';import assert from 'node:assert/strict';
import {EXPEDITION_STYLES,expeditionArtIcon,expeditionStyle} from '../shared/config/expedition-art.mjs';
import {normalizeExpeditionPiece,publicExpeditionPiece,selectExpeditionStyle,moveExpeditionPiece,cancelExpeditionMovement,placeExpeditionPiece} from '../server/domain/expedition-piece.mjs';
import {CampaignService} from '../campaign-service.mjs';
import {createCampaignApiHandler} from '../server/http/campaign-api-handler.mjs';
import {expeditionAppearanceMarkup} from '../client/map/expedition-appearance-controller.js';
function fixture(){return {account:{id:'a',setupComplete:true,homeTerritoryId:'home',expeditionPiece:{schemaVersion:1,tokenId:'default',territoryId:'home',movement:null}},world:{territories:{home:{ownerType:'player',ownerId:'a'},next:{ownerType:'player',ownerId:'a'}},players:{a:{territoryIds:['home','next']}}},territoryIndex:{territories:[{territoryId:'home',centroid:[0,0]},{territoryId:'next',centroid:[3,0]}]}};}
test('legacy default and unknown saved appearances recover safely without resetting movement',()=>{const f=fixture();assert.equal(publicExpeditionPiece(f.account,f.world,1000).styleId,'airplane');moveExpeditionPiece({...f,targetTerritoryId:'next',now:1000});const motion=structuredClone(f.account.expeditionPiece.movement);f.account.expeditionPiece.tokenId='obsolete';assert.equal(normalizeExpeditionPiece(f.account,f.world,2000).changed,true);assert.equal(f.account.expeditionPiece.tokenId,'default');assert.deepEqual(f.account.expeditionPiece.movement,motion);});
test('all five appearances persist through normalization, travel, cancel, serialized reload and conquest placement',()=>{for(const style of EXPEDITION_STYLES){const f=fixture();selectExpeditionStyle(f.account,f.world,style.id,1000);moveExpeditionPiece({...f,targetTerritoryId:'next',now:1000});const motion=structuredClone(f.account.expeditionPiece.movement);selectExpeditionStyle(f.account,f.world,style.id,2000);assert.deepEqual(f.account.expeditionPiece.movement,motion);assert.equal(publicExpeditionPiece(f.account,f.world,2000).tokenUrl,expeditionArtIcon(style.id));cancelExpeditionMovement(f.account,f.world,3000);const restored=JSON.parse(JSON.stringify(f.account));placeExpeditionPiece(restored,'next');assert.equal(publicExpeditionPiece(restored,f.world,4000).styleId,style.id);assert.equal(restored.expeditionPiece.territoryId,'next');}});
test('invalid selections never mutate the account and undeployed players cannot select',()=>{const f=fixture(),before=structuredClone(f.account);for(const id of ['../secret','',null,{},'MESSI']){assert.throws(()=>selectExpeditionStyle(f.account,f.world,id,1000),/未知/);assert.deepEqual(f.account,before);}assert.throws(()=>selectExpeditionStyle({id:'none'},f.world,'airplane'),/请先完成/);});
test('appearance service persists the authenticated account and restores the previous piece on save failure',()=>{const f=fixture();let written;const host={world:f.world,now:()=>1000,save(){written=JSON.parse(JSON.stringify(f.account));},state(a){return {expeditionPiece:publicExpeditionPiece(a,f.world,1000)};}};const result=CampaignService.prototype.selectExpeditionAppearance.call(host,f.account,'tank');assert.equal(result.state.expeditionPiece.styleId,'tank');assert.equal(written.expeditionPiece.tokenId,'tank');const before=structuredClone(f.account);host.save=()=>{throw Error('disk failure');};assert.throws(()=>CampaignService.prototype.selectExpeditionAppearance.call(host,f.account,'excavator'),/disk failure/);assert.deepEqual(f.account,before);});
test('appearance endpoint authenticates and ignores client account selection',async()=>{const calls=[],a={id:'authenticated'};const handler=createCampaignApiHandler({campaign:{authenticate(token){if(token!=='auth')throw Object.assign(Error('请登录'),{statusCode:401});return a;},selectExpeditionAppearance(account,id){calls.push([account,id]);return {ok:true};}}});const res=()=>({status:null,text:'',writeHead(status){this.status=status;},end(v){this.text=v;}});const req=(auth)=>({method:'POST',headers:{authorization:auth},async *[Symbol.asyncIterator](){yield Buffer.from(JSON.stringify({tokenId:'sports-car',accountId:'victim',playerId:'victim'}));}});const ok=res();await handler(req('Bearer auth'),ok,'/api/campaign/expedition/appearance','/api/campaign/expedition/appearance');assert.equal(ok.status,200);assert.deepEqual(calls,[[a,'sports-car']]);const denied=res();await assert.rejects(()=>handler(req('Bearer bad'),denied,'/api/campaign/expedition/appearance','/api/campaign/expedition/appearance'),error=>error.statusCode===401);assert.equal(calls.length,1);});
test('selection markup distinguishes previewed and saved choices and escapes failed-save messages',()=>{const html=expeditionAppearanceMarkup('tank','airplane');assert.equal((html.match(/data-expedition-style="/g)||[]).length,5);assert.match(html,/data-expedition-style="tank" aria-pressed="true"/);assert.ok(html.includes('当前使用'));assert.match(expeditionAppearanceMarkup('airplane','default'),/data-expedition-style-apply disabled/);assert.match(expeditionAppearanceMarkup('tank','airplane',{busy:true}),/保存中/);assert.ok(!expeditionAppearanceMarkup('tank','airplane',{error:'<script>x</script>'}).includes('<script>'));assert.equal(expeditionStyle('default').id,'airplane');});

test('all retired athlete IDs migrate once while retaining the existing travel route',()=>{
 for(const [old,id]of Object.entries({messi:'airplane',ronaldo:'excavator',mbappe:'bus',yamal:'sports-car',haaland:'tank'})){
  const f=fixture();moveExpeditionPiece({...f,targetTerritoryId:'next',now:1000});f.account.expeditionPiece.tokenId=old;const before=structuredClone(f.account.expeditionPiece);
  assert.equal(normalizeExpeditionPiece(f.account,f.world,2000).changed,true);assert.equal(f.account.expeditionPiece.tokenId,id);assert.deepEqual(f.account.expeditionPiece.movement,before.movement);assert.equal(f.account.expeditionPiece.territoryId,before.territoryId);
  assert.equal(normalizeExpeditionPiece(f.account,f.world,2000).changed,false);assert.equal(publicExpeditionPiece(f.account,f.world,2000).tokenUrl,expeditionArtIcon(id));
 }
});
