import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import {createHash} from 'node:crypto';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {FACILITY_ART_VERSION,FACILITY_ART,FACILITY_MODEL_ART,INDUSTRY_ACADEMY_ART,FACILITY_ASSET_ITEMS,facilityArtIcon,unitArtIcon} from '../shared/config/facility-art.mjs';
import {BUILDING_DEFINITIONS,BUILDING_RULES} from '../shared/config/buildings.mjs';
import {createFacilityModel,inspectFacilityModel,disposeFacilityModel} from '../client/facility-models/facility-models.js';
import {buildingMarkerMarkup} from '../client/buildings/building-marker-controller.js';import {buildingPanelMarkup} from '../client/buildings/building-panel-controller.js';import {publicRequestPath} from '../server/http/static-handler.mjs';
const root=new URL('../',import.meta.url),catalog=JSON.parse(await fs.readFile(new URL('assets/facilities/catalog.json',root),'utf8'));
test('facilities use their configured level counts, and both independent units have no invented levels',()=>{
 assert.equal(catalog.version,FACILITY_ART_VERSION);assert.equal(catalog.items.length,FACILITY_ASSET_ITEMS.length);assert.deepEqual(new Set(FACILITY_ART.map(i=>i.type)),new Set(Object.keys(BUILDING_DEFINITIONS)));assert.deepEqual(new Set(catalog.items.map(i=>i.assetId)),new Set(FACILITY_ASSET_ITEMS.map(i=>i.assetId)));
 for(const f of FACILITY_MODEL_ART){const models=catalog.items.filter(i=>i.type===f.type);const count=f.planned?f.levels.length:BUILDING_DEFINITIONS[f.type].costsGold.length;assert.deepEqual(models.map(i=>i.level),Array.from({length:count},(_,i)=>i+1));assert.equal(new Set(models.map(i=>i.files[0].sha256)).size,count);assert.equal(new Set(models.map(i=>i.change)).size,count);for(let i=1;i<count;i++)assert.ok(models[i].levels[0].triangles>models[i-1].levels[0].triangles);}
 assert.equal(catalog.items.filter(i=>i.kind==='unit').length,2);assert.ok(catalog.items.filter(i=>i.kind==='unit').every(i=>i.level===null));assert.equal(BUILDING_RULES.upgradesEnabled,true);
});
for(const item of catalog.items)test(item.assetId+': portable GLBs retain geometry, authored colors and stable ground alignment at three LODs',async()=>{
 for(let lod=0;lod<3;lod++){const f=item.files[lod],bytes=await fs.readFile(new URL(f.url,root));assert.equal(bytes.readUInt32LE(0),0x46546c67);assert.equal(bytes.readUInt32LE(4),2);assert.equal(bytes.readUInt32LE(8),bytes.length);assert.equal(bytes.length,f.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),f.sha256);let offset=12,doc;while(offset<bytes.length){const len=bytes.readUInt32LE(offset),type=bytes.readUInt32LE(offset+4);assert.equal(len%4,0);assert.ok(offset+8+len<=bytes.length);if(type===0x4e4f534a)doc=JSON.parse(bytes.subarray(offset+8,offset+8+len).toString());offset+=8+len;}assert.equal(offset,bytes.length);assert.equal(doc.asset.version,'2.0');assert.ok(!doc.images?.length);assert.ok(doc.buffers.every(b=>!b.uri));
 const gltf=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.length),''),stats=inspectFacilityModel(gltf.scene),fresh=createFacilityModel(item.assetId,{lod});assert.equal(stats.triangles,item.levels[lod].triangles);assert.equal(stats.triangles,inspectFacilityModel(fresh).triangles);assert.ok(Math.abs(stats.bounds.min[1])<1e-5);assert.ok(Math.abs(Math.max(stats.size[0],stats.size[2])-1)<1e-5);assert.ok(stats.triangles>100);if(lod)assert.ok(stats.triangles<item.levels[lod-1].triangles);
 const colors=m=>{const seen=new Set();m.traverse(o=>{if(!o.isMesh)return;const p=o.geometry.attributes.position,n=o.geometry.attributes.normal;assert.equal(p.count,n.count);for(const v of p.array)assert.ok(Number.isFinite(v));for(const v of n.array)assert.ok(Number.isFinite(v));for(const i of o.geometry.index?.array??[])assert.ok(i>=0&&i<p.count);assert.equal(o.material.userData.artVersion,FACILITY_ART_VERSION);seen.add(o.material.color.getHexString()+'|'+o.material.roughness.toFixed(5)+'|'+o.material.metalness.toFixed(5));});return seen;};assert.deepEqual(colors(gltf.scene),colors(fresh));assert.ok(gltf.scene.getObjectByName('foundation'));if(item.type==='expedition')for(const node of ['team_banner','football','captain_head','squad_left_head','squad_right_head'])assert.ok(gltf.scene.getObjectByName(node),node);if(item.type==='scout')for(const node of ['map','binoculars','satchel','scout_hat'])assert.ok(gltf.scene.getObjectByName(node),node);disposeFacilityModel(fresh);disposeFacilityModel(gltf.scene);
 }
});
test('level artwork is selected consistently in game details and markers, while unknown facilities retain their supplied icon',async()=>{
 for(const f of FACILITY_ART)for(let level=1;level<=5;level++){const expected=facilityArtIcon(f.type,level),b={id:'b',type:f.type,level,status:'active'},definition=BUILDING_DEFINITIONS[f.type];assert.ok(buildingMarkerMarkup({buildings:[b],catalog:[definition]}).includes(expected));assert.ok(buildingPanelMarkup({view:{buildings:[b]},catalog:[definition]}).includes(expected));const icon=await fs.readFile(new URL(expected.slice(1).split('?')[0],root));assert.equal(icon.readUInt32BE(0),0x89504e47);}
 assert.equal(facilityArtIcon('unregistered',2),null);assert.ok(buildingMarkerMarkup({buildings:[{id:'x',type:'unregistered',iconPath:'/custom.png'}]}).includes('/custom.png'));assert.equal(facilityArtIcon('port',99),facilityArtIcon('port',5));assert.ok(unitArtIcon('scout').includes('/scout.png'));
});
test('model identifiers and static files stay within expected asset paths',()=>{
 assert.throws(()=>createFacilityModel('../data'),/Unknown facility/);assert.throws(()=>createFacilityModel('port-lv1',{lod:3}),/LOD/);assert.equal(publicRequestPath('/assets/facilities/models/port-lv5.glb'),'assets/facilities/models/port-lv5.glb');assert.equal(publicRequestPath('/server/facilities.glb'),null);
});

test('university and factory are complete five-level economic facilities with gameplay registration',async()=>{
 assert.deepEqual(INDUSTRY_ACADEMY_ART.map(i=>i.type),['university','factory']);
 for(const f of INDUSTRY_ACADEMY_ART){assert.equal(BUILDING_DEFINITIONS[f.type].maxPerPlayer,1);assert.ok(facilityArtIcon(f.type));
  for(let level=1;level<=5;level++){const item=catalog.items.find(i=>i.assetId===`${f.type}-lv${level}`);assert.ok(item.newFacility);assert.equal(item.files.length,3);const png=await fs.readFile(new URL(item.icon,root));assert.equal(png.readUInt32BE(0),0x89504e47);}
 }
});
