import test from 'node:test';
import assert from 'node:assert/strict';
import {RESEARCH_BRANCHES,RESEARCH_TOPICS,normalizeResearchSelection,researchLevelPreview} from '../shared/config/research-preview.mjs';
import {s4EnhancementChanceForLevels,S4_ENHANCEMENT} from '../shared/config/enhancement.mjs';
import {researchTreeLayout} from '../client/research/research-layout.js';
import {researchDetails} from '../client/research/research-controller.js';
test('four directions include playable biology endurance research',()=>{assert.deepEqual(RESEARCH_BRANCHES.map(b=>b.id),['formation','tactic','enhancement','biology']);assert.equal(RESEARCH_TOPICS.filter(t=>t.branch==='biology').length,1);});
test('routes contain only successive levels for their chosen object',()=>{for(const topic of RESEARCH_TOPICS){const tree=researchTreeLayout(topic),count=topic.branch==='enhancement'?10:5;assert.equal(tree.nodes.length,count);assert.equal(tree.edges.length,count-1);assert.ok(tree.nodes.every(n=>n.topicId===topic.id));for(const [i,edge]of tree.edges.entries()){assert.equal(edge.from,tree.nodes[i].id);assert.equal(edge.to,tree.nodes[i+1].id);}assert.equal(tree.nodes.at(-1).bonus,topic.branch==='biology'?15:5);}});
test('tactic levels are cumulative one to five percent, never compounded',()=>{for(const t of RESEARCH_TOPICS.filter(t=>t.branch==='tactic')){assert.deepEqual([1,2,3,4,5].map(l=>researchLevelPreview(t,l).result),[1,2,3,4,5]);assert.throws(()=>researchLevelPreview(t,6));}});
test('every fallible enhancement pairing follows actual main and material probability',()=>{const list=RESEARCH_TOPICS.filter(t=>t.branch==='enhancement');for(let main=0;main<S4_ENHANCEMENT.maxLevel;main++)for(let material=0;material<=S4_ENHANCEMENT.maxLevel;material++){const chance=s4EnhancementChanceForLevels(main,material),topic=list.find(t=>t.main===main&&t.material===material);assert.equal(!!topic,chance<100&&material<=main);if(topic){assert.equal(topic.baseChance,chance);assert.equal(topic.target,main+1);}}assert.equal(list.find(t=>t.id==='enhancement:2:1').baseChance,57);});
test('ten enhancement levels add half percentage point each and cap final probability',()=>{const topic=RESEARCH_TOPICS.find(t=>t.id==='enhancement:2:1');assert.equal(researchLevelPreview(topic,1).result,57.5);assert.equal(researchLevelPreview(topic,10).result,62);assert.equal(researchLevelPreview({...topic,baseChance:99},10).result,100);assert.throws(()=>researchLevelPreview(topic,11));assert.throws(()=>researchLevelPreview(topic,0));assert.match(researchDetails(topic,1),/57.5%/);assert.match(researchDetails(topic,10),/62%/);});
test('saved selections reject old target-only enhancement ids and cross-branch ids',()=>{assert.deepEqual(normalizeResearchSelection({formation:'style:lowBlock',tactic:'formation:4-3-3',enhancement:'enhancement:8'}),{formation:null,tactic:null,enhancement:null,biology:null});assert.equal(normalizeResearchSelection({enhancement:'enhancement:2:1'}).enhancement,'enhancement:2:1');});

test('preset formations are retired from selectable research topics',()=>{assert.ok(!RESEARCH_TOPICS.some(t=>t.branch==='formation'));assert.equal(normalizeResearchSelection({formation:'formation:4-3-3'}).formation,null);});
