import test from 'node:test';import assert from 'node:assert/strict';import {coalitionFixture} from './coalition-fixture.mjs';import {territoryTradeChoices} from '../server/application/territory-trade.mjs';
import {purchaseFixture} from './card-purchase-fixture.mjs';
function fixture(){const f=coalitionFixture();for(const [id,owner]of [['land-a','a'],['land-b','b']]){f.s.world.territories[id]={...structuredClone(f.s.world.territories[owner]),ownerId:owner,capitalOf:null,version:1,originalOwnerId:owner,buildings:[]};f.s.world.players[owner].territoryIds.push(id);f.s.territoryIndex.territories.push({...f.s.territoryIndex.territories[0],territoryId:id,name:id});}return f;}
const offer=(f,trade)=>f.s.diplomacy.mutate(f.a,{action:'trade',targetId:'b',requestId:'land-offer-1',trade});
const accept=(f,id)=>f.s.diplomacy.mutate(f.b,{action:'accept',targetId:'a',proposalId:id,requestId:'land-accept-1'});

test('historical raids, scout origins and move receipts do not reserve land in either trading entry',()=>{
 const f=purchaseFixture(),id=f.land;
 (f.a.scouting??={}).units={scout:{id:'scout',territoryId:'a',originTerritoryId:id,originBuildingId:'old-port',movement:null,moveRequests:{old:{result:{territoryId:id,movement:{path:[id,'a']}}}}}};
 f.a.expeditionPiece.lastMove={fromTerritoryId:id};
 f.s.world.eliteRaids={days:{old:{endsAt:f.now-1,raids:[{status:'withdrawn',index:0,route:[{territoryId:id}],results:[{territoryId:id}]}]}},matches:{},history:[{territoryId:id}]};
 assert.ok(territoryTradeChoices(f.s,f.a,f.b).give.some(t=>t.id===id));
 assert.ok(f.s.cardPurchases.options(f.a).territories.some(t=>t.id===id));
 const {orderId}=f.publish();assert.ok(orderId);f.accept(orderId);assert.equal(f.s.world.territories[id].ownerId,'b');
});

test('only live raid stops and battles block trade; completed stops and future targets stay available',()=>{
 for(const live of [
  {days:{today:{endsAt:Infinity,raids:[{status:'moving',index:1,route:[{territoryId:'land-b'},{territoryId:'land-a'}],movement:{fromTerritoryId:'a',toTerritoryId:'land-a'}}]}},matches:{}},
  {days:{today:{endsAt:Infinity,raids:[{status:'waiting',index:0,route:[{territoryId:'land-a'}]}]}},matches:{}},
  {days:{},matches:{battle:{territoryId:'land-a'}}},
 ]){const f=fixture();f.s.world.eliteRaids=live;assert.throws(()=>offer(f,{giveTerritoryIds:['land-a']}),/任务/);assert.ok(territoryTradeChoices(f.s,f.a,f.b).take.some(t=>t.id==='land-b'));}
 const f=fixture();f.s.world.eliteRaids={days:{today:{endsAt:f.now+1000,raids:[{status:'moving',index:1,route:[{territoryId:'land-a'},{territoryId:'a'},{territoryId:'land-b'}]}]}},matches:{},history:[]};
 assert.ok(territoryTradeChoices(f.s,f.a,f.b).give.some(t=>t.id==='land-a'));assert.ok(territoryTradeChoices(f.s,f.a,f.b).take.some(t=>t.id==='land-b'));
});

test('current scouts and active movement paths still block both trade choices and purchase payment',()=>{
 for(const unit of [{territoryId:'purchase-land'},{territoryId:'a',movement:{path:['a','purchase-land','b']}}]){const f=purchaseFixture();(f.a.scouting??={}).units={scout:unit};assert.ok(!territoryTradeChoices(f.s,f.a,f.b).give.some(t=>t.id===f.land));assert.ok(!f.s.cardPurchases.options(f.a).territories.some(t=>t.id===f.land));assert.throws(()=>f.publish(),/任务/);}
});
test('land and ordinary buildings swap with gold atomically and replay never duplicates',()=>{const f=fixture(),t=f.s.world.territories['land-a'];t.buildings=[{id:'port-1',type:'port',status:'active',level:2,name:'港口'}];t.protectedUntil=f.now+90000;const building=structuredClone(t.buildings);const {proposalId}=offer(f,{giveTerritoryIds:['land-a'],takeTerritoryIds:['land-b'],takeGold:500});const before=f.a.gold;accept(f,proposalId);assert.equal(t.ownerId,'b');assert.equal(t.originalOwnerId,'b');assert.equal(t.protectedUntil,f.now+90000);assert.deepEqual(t.buildings,building);assert.equal(f.a.gold,before+500);assert.ok(f.s.world.players.b.territoryIds.includes('land-a'));assert.equal(f.s.world.territories['land-b'].ownerId,'a');accept(f,proposalId);assert.equal(f.a.gold,before+500);f.reload();assert.equal(f.s.world.territories['land-a'].ownerId,'b');});
test('capitals, unique buildings, wonders, upgrades, units, suppression and war are rejected',()=>{for(const change of [f=>f.s.world.territories['land-a'].capitalOf='a',f=>f.s.world.territories['land-a'].buildings=[{type:'factory',status:'active'}],f=>f.s.world.territories['land-a'].buildings=[{type:'port',wonderId:'wonder',status:'active'}],f=>f.s.world.territories['land-a'].buildings=[{type:'port',status:'active',upgradeTo:2}],f=>f.a.expeditionPiece.territoryId='land-a',f=>f.s.world.territories['land-a'].raidSuppression={},f=>f.s.world.diplomacy.relationships[JSON.stringify(['a','b'])].state='war']){const f=fixture();change(f);assert.throws(()=>offer(f,{giveTerritoryIds:['land-a']}));}});
test('changed land invalidates old quote before paying',()=>{const f=fixture(),{proposalId}=offer(f,{giveTerritoryIds:['land-a'],takeGold:500}),gold=f.b.gold;f.s.world.territories['land-a'].version++;assert.throws(()=>accept(f,proposalId),/变化/);assert.equal(f.b.gold,gold);assert.equal(f.s.world.territories['land-a'].ownerId,'a');});
test('persistence failure after transfer restores ownership, buildings, player lists, gold and proposal',()=>{const f=fixture(),{proposalId}=offer(f,{giveTerritoryIds:['land-a'],takeGold:500});const before=structuredClone({t:f.s.world.territories['land-a'],players:f.s.world.players,gold:f.a.gold});const persist=f.s.persist.bind(f.s);let n=0;f.s.persist=()=>{if(++n===2)throw Error('disk failure');persist();};assert.throws(()=>accept(f,proposalId),/disk failure/);assert.deepEqual(f.s.world.territories['land-a'],before.t);assert.deepEqual(f.s.world.players,before.players);assert.equal(f.a.gold,before.gold);assert.equal(f.s.world.diplomacy.requests[proposalId].status,'pending');});
test('selection list is compact, excludes capital, and gift cannot demand land',()=>{const f=fixture(),choices=territoryTradeChoices(f.s,f.a,f.b);assert.deepEqual(choices.give.map(x=>x.id),['land-a']);assert.ok(JSON.stringify(choices).length<1000);assert.throws(()=>offer(f,{mode:'gift',takeTerritoryIds:['land-b']}),/赠送/);assert.throws(()=>offer(f,{giveTerritoryIds:['land-a','land-a']}),/3块/);});
test('compact expedition cancellation avoids full state and rolls back failed persistence',()=>{const f=fixture(),movement={id:'trip-123',fromTerritoryId:'a',toTerritoryId:'b',path:['a','b'],startedAt:f.now,arrivesAt:f.now+60000,durationMs:60000};f.a.expeditionPiece.movement=movement;f.s.economyDue=()=>false;f.s.state=()=>{throw Error('full state must not be built');};f.fail(true);assert.throws(()=>f.s.cancelExpedition(f.a,{compact:true,movementId:movement.id}),/disk failure/);assert.deepEqual(f.a.expeditionPiece.movement,movement);f.fail(false);const result=f.s.cancelExpedition(f.a,{compact:true,movementId:movement.id});assert.equal(result.state,undefined);assert.equal(result.statePatch.expeditionPiece.moving,false);assert.equal(f.a.expeditionPiece.movement,null);});

test('ordinary building jobs block trade through building identity even without territoryId',()=>{const f=fixture();f.s.world.territories['land-a'].buildings=[{id:'training-1',type:'training-center',level:1,status:'active'}];f.a.training={tasks:{job:{id:'job',buildingId:'training-1'}}};assert.throws(()=>offer(f,{giveTerritoryIds:['land-a']}),/任务/);});
test('land quote snapshots only participants and uses one persist when economy is current',()=>{const f=fixture();f.s.economyDue=()=>false;let saveCalls=0,persistCalls=0;const save=f.s.save.bind(f.s),persist=f.s.persist.bind(f.s);f.s.save=()=>{saveCalls++;return save();};f.s.persist=()=>{persistCalls++;return persist();};offer(f,{giveTerritoryIds:['land-a']});assert.equal(saveCalls,0);assert.equal(persistCalls,1);});
test('compact scout cancellation returns scouting only and persists without global settlement when current',()=>{const f=fixture();f.s.economyDue=()=>false;f.s.state=()=>{throw Error('full state forbidden');};f.a.scouting={schemaVersion:2,tasks:{},units:{scout:{id:'scout',name:'Scout',territoryId:'a',movement:{id:'scout-trip',fromTerritoryId:'a',toTerritoryId:'b',startedAt:f.now,arrivesAt:f.now+60000,durationMs:60000}}}};const result=f.s.cancelScoutMove(f.a,'scout','scout-trip',{compact:true});assert.equal(result.state,undefined);assert.equal(result.scout.movement,null);assert.deepEqual(Object.keys(result.statePatch),['scouting']);});
