const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
const state = { token:localStorage.getItem("ydl-admin-token") || "", profile:null, page:"players", overview:null, players:[], selectedId:null, selectedPublish:new Set(), audit:[], tasks:[], studioFile:null, packManagement:null, selectedAccountId:null, grantAllPlayers:false };
let playerCardMarkup = (player) => `<div class="s4-player-card admin-card-preview"><div class="s4-player-card-name"><h3>${escapeHtml(player?.name ?? "球员")}</h3></div></div>`;

const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", '"':"&quot;", "'":"&#39;" })[character]);
async function api(url, options = {}) {
  const headers = { ...(options.headers ?? {}) };
  if (state.token) headers.authorization = `Bearer ${state.token}`;
  if (options.body !== undefined) headers["content-type"] = "application/json";
  const response = await fetch(url, { ...options, headers, body:options.body === undefined ? undefined : JSON.stringify(options.body) });
  const value = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(value.error ?? `请求失败：${response.status}`);
  return value;
}
function toast(message, error = false) { const node = $("#toast"); node.textContent = message; node.className = `toast${error ? " error" : ""}`; node.hidden = false; clearTimeout(toast.timer); toast.timer = setTimeout(() => { node.hidden = true; }, 3200); }
function selectedPlayer() { return state.players.find((player) => player.id === state.selectedId) ?? null; }
function distributionMarkup(title, values = []) { const maximum = Math.max(1, ...values.map((item) => item.count)); return `<section class="panel"><header class="panel-head"><h3>${escapeHtml(title)}</h3></header><div class="distribution">${values.slice(0, 18).map((item) => `<div><span>${escapeHtml(item.label)}</span><i><span style="width:${item.count / maximum * 100}%"></span></i><b>${item.count}</b></div>`).join("") || '<p class="empty">暂无数据</p>'}</div></section>`; }

async function loadAll() {
  const [overview, players, audit, tasks, packManagement] = await Promise.all([
    api("/api/admin/player-library"), api("/api/admin/player-library/players"), api("/api/admin/audit?limit=100"), api("/api/admin/tasks"), api("/api/admin/player-packs"),
  ]);
  state.overview = overview; state.players = players.players; state.audit = audit.entries; state.tasks = tasks.tasks; state.packManagement = packManagement;
  if (!state.players.some((player) => player.id === state.selectedId)) state.selectedId = state.players[0]?.id ?? null;
  if (!state.packManagement.players.some((player) => player.id === state.selectedAccountId)) state.selectedAccountId = state.packManagement.players[0]?.id ?? null;
  render();
}
async function login(event) {
  event.preventDefault();
  const form = event.currentTarget;
  const error = $("#login-error");
  const button = $("#login-submit");
  error.textContent = "正在验证管理员身份…";
  button.disabled = true;
  button.textContent = "正在登录…";
  try {
    const value = await api("/api/admin/login", { method:"POST", body:Object.fromEntries(new FormData(form)) });
    state.token = value.token;
    state.profile = value.profile;
    localStorage.setItem("ydl-admin-token", state.token);
    showAdmin();
    try {
      await loadAll();
    } catch (loadFailure) {
      $("#app").innerHTML = `<div class="loading">工作台数据加载失败：${escapeHtml(loadFailure.message)}</div>`;
      toast(loadFailure.message || "工作台数据加载失败",true);
    }
  } catch (failure) {
    error.textContent = failure.message || "管理员登录失败";
  } finally {
    button.disabled = false;
    button.textContent = "进入工作台";
  }
}
function showAdmin() { $("#login-view").hidden = true; $("#admin-view").hidden = false; $("#admin-role").textContent = `${state.profile?.username ?? "admin"} · ${state.profile?.role ?? ""}`; }
function logout() { state.token = ""; state.profile = null; localStorage.removeItem("ydl-admin-token"); location.reload(); }

function pageHead(kicker, title, description, actions = "") { return `<header class="page-head"><div><small>${kicker}</small><h1>${title}</h1><p>${description}</p></div><div class="head-actions">${actions}</div></header>`; }
function kpisMarkup() { const a = state.overview.audit; return `<section class="kpis"><article class="kpi"><small>生产球员</small><b>${a.activePlayers}</b></article><article class="kpi"><small>暂存新卡</small><b>${state.overview.drafts}</b></article><article class="kpi"><small>已登记卡画</small><b>${a.profileEntries}</b></article><article class="kpi"><small>生产库卡画覆盖率</small><b>${a.profileCoverage}%</b></article><article class="kpi ${a.missingAssets.length ? "warn" : ""}"><small>缺失卡画文件</small><b>${a.missingAssets.length}</b></article></section>`; }

function filterPlayers() {
  const search = $("#player-search")?.value.trim().toLowerCase() ?? ""; const grade = $("#player-grade")?.value ?? "all"; const role = $("#player-role")?.value ?? "all"; const profile = $("#player-profile")?.value ?? "all";
  return state.players.filter((player) => (grade === "all" || player.grade === grade) && (role === "all" || player.role === role) && (profile === "all" || (profile === "present" ? player.profile : !player.profile)) && (!search || `${player.id} ${player.name} ${player.sourceName ?? ""} ${player.club} ${player.nationality}`.toLowerCase().includes(search)));
}
function playerRows(studio = false) {
  const rows = filterPlayers();
  return rows.map((player) => `<div class="player-row ${player.id === state.selectedId ? "active" : ""}" data-player-row="${escapeHtml(player.id)}">
    <b class="grade grade-${player.grade.toLowerCase()}">${player.grade}</b><button type="button" data-player="${escapeHtml(player.id)}" style="display:block;min-width:0;padding:0;border:0;background:transparent;text-align:left;color:inherit"><strong>${escapeHtml(player.name)}</strong><small>${escapeHtml(player.id)} · ${escapeHtml(player.club)} · ${escapeHtml(player.nationality)}</small></button><em>${player.role} · ${player.overall}</em><i class="${player.profile ? "has" : ""}">${player.profile ? "已有卡画" : "缺少卡画"}</i>${studio && player.status === "draft" ? `<input type="checkbox" data-publish="${escapeHtml(player.id)}" ${state.selectedPublish.has(player.id) ? "checked" : ""} title="加入批量上线">` : ""}
  </div>`).join("") || '<p class="empty">没有符合条件的球员</p>';
}
function filtersMarkup() { const meta = state.overview; return `<div class="filters"><input id="player-search" placeholder="搜索球员、ID、俱乐部或国籍"><select id="player-grade"><option value="all">全部等级</option>${meta.grades.map((value) => `<option>${value}</option>`).join("")}</select><select id="player-role"><option value="all">全部位置</option>${meta.roles.map((value) => `<option>${value}</option>`).join("")}</select><select id="player-profile"><option value="all">全部卡画</option><option value="present">已有卡画</option><option value="missing">缺少卡画</option></select></div>`; }
function inputField(name, label, value, options = null, extraClass = "") { return `<label class="${extraClass}">${label}${options ? `<select name="${name}">${options.map((option) => `<option value="${escapeHtml(option.value ?? option)}" ${(option.value ?? option) === value ? "selected" : ""}>${escapeHtml(option.label ?? option ?? "无")}</option>`).join("")}</select>` : `<input name="${name}" value="${escapeHtml(value ?? "")}">`}</label>`; }
function editorMarkup(player) {
  if (!player) return '<div class="editor-empty">从左侧选择一名球员</div>';
  const meta = state.overview; const secondary = [{ value:"", label:"无" }, ...meta.roles];
  return `<form id="player-form" class="editor-form"><header class="panel-head" style="margin:-16px -16px 0"><div><small>${player.status === "draft" ? "STAGING CARD" : "PRODUCTION PLAYER"}</small><h2>${escapeHtml(player.name)}</h2></div><b>${escapeHtml(player.id)}</b></header><h3 class="section-title">基础资料</h3><div class="form-grid">
    ${inputField("name","球员姓名",player.name,null,"wide")}${inputField("sourceName","英文/来源名",player.sourceName,null,"wide")}${inputField("grade","评级",player.grade,meta.grades)}${inputField("role","主位置",player.role,meta.roles)}${inputField("secondaryRole","副位置",player.secondaryRole,secondary)}${inputField("preferredFoot","惯用脚",player.preferredFoot,[{value:"right",label:"右脚"},{value:"left",label:"左脚"},{value:"both",label:"双足"}])}${inputField("nationality","国籍",player.nationality,null,"wide")}${inputField("club","俱乐部",player.club,null,"wide")}${inputField("heightCm","身高 cm",player.heightCm)}<label>当前总评<input value="${player.overall}" disabled></label>
  </div><h3 class="section-title">26 项生产属性 · 保存后按 YDL 位置算法重算总评</h3><div class="attribute-grid">${meta.attributeNames.map((key) => `<label>${escapeHtml(meta.attributeLabels[key])}<input name="attr.${key}" type="number" min="1" max="99" value="${player.attributes[key]}"></label>`).join("")}</div><div class="savebar"><output id="player-save-status"></output><span>${player.profile ? "卡画已登记" : "卡画待补"}</span><button class="primary" type="submit">保存球员资料</button></div></form>`;
}
function renderPlayers() { $("#app").innerHTML = `${pageHead("YDL PLAYER LIBRARY","球员库管理","生产目录、运营覆盖与 26 项能力值统一维护。",'<button id="new-player">+ 制作新卡</button><button id="batch-import">批量制卡</button>')}${kpisMarkup()}<section class="workspace"><aside class="panel"><header class="panel-head"><div><h2>正式库与暂存池</h2><small>${state.players.length} 条可维护记录</small></div></header>${filtersMarkup()}<div class="player-list" id="player-list">${playerRows()}</div></aside><section class="panel editor" id="player-editor">${editorMarkup(selectedPlayer())}</section></section>`; bindPlayerWorkspace(false); $("#new-player").onclick = () => openDraftDialog(); $("#batch-import").onclick = openBatchDialog; }

function cardMarkup(player) { return playerCardMarkup(player, { variant:"detail", id:"card-preview", imageId:"card-image", showArtPlaceholder:true, className:"admin-card-preview" }); }
function studioEditor(player) { if (!player) return '<div class="editor-empty">从左侧选择一名球员</div>'; const p = player.profile ?? { x:50,y:52,width:200 }; return `<header class="panel-head"><div><small>CARD ART POSITIONER</small><h2>${escapeHtml(player.name)}</h2></div><span>${player.profile ? "已登记卡画" : "待补卡画"}</span></header><div class="studio-stage">${cardMarkup(player)}</div><div class="studio-controls"><label class="upload"><span id="upload-label">选择 PNG 或 WebP；浏览器会转为 1600px WebP</span><input id="profile-file" type="file" accept="image/png,image/webp"></label>${[["x","横向位置",-50,150,p.x],["y","纵向位置",-50,150,p.y],["width","人物宽度",40,360,p.width]].map(([key,label,min,max,value]) => `<label>${label} <b data-position-value="${key}">${Number(value).toFixed(1)}%</b><input type="range" data-position="${key}" min="${min}" max="${max}" step=".1" value="${value}"></label>`).join("")}<div class="studio-actions"><button id="reset-position">重置定位</button><button class="primary" id="save-profile">保存卡画与定位</button></div></div>`; }
function renderStudio() { $("#app").innerHTML = `${pageHead("YDL PLAYER CARD STUDIO","球员卡工作室","上传抠图、实时定位、新卡暂存与批量上线。",`<button id="publish-selected" class="primary" ${state.selectedPublish.size ? "" : "disabled"}>批量上线（${state.selectedPublish.size}）</button>`)}<section class="studio-layout"><aside class="panel"><header class="panel-head"><div><h2>卡画资产目录</h2><small>正式球员与暂存新卡</small></div></header>${filtersMarkup()}<div class="player-list" id="player-list">${playerRows(true)}</div></aside><main class="panel" id="studio-editor">${studioEditor(selectedPlayer())}</main></section>`; bindPlayerWorkspace(true); $("#publish-selected").onclick = publishSelected; bindStudio(); }
function bindPlayerWorkspace(studio) {
  ["#player-search","#player-grade","#player-role","#player-profile"].forEach((selector) => { const node=$(selector); node.addEventListener(selector.includes("search") ? "input" : "change", () => { $("#player-list").innerHTML = playerRows(studio); bindRows(studio); }); }); bindRows(studio); if (!studio) bindPlayerForm();
}
function bindRows(studio) { $$('[data-player]').forEach((button) => button.onclick = () => { state.selectedId = button.dataset.player; if (studio) { $("#studio-editor").innerHTML = studioEditor(selectedPlayer()); bindStudio(); } else { $("#player-editor").innerHTML = editorMarkup(selectedPlayer()); bindPlayerForm(); } $$(".player-row").forEach((row) => row.classList.toggle("active", row.dataset.playerRow === state.selectedId)); }); $$('[data-publish]').forEach((checkbox) => checkbox.onchange = () => { checkbox.checked ? state.selectedPublish.add(checkbox.dataset.publish) : state.selectedPublish.delete(checkbox.dataset.publish); renderStudio(); }); }
function bindPlayerForm() { $("#player-form")?.addEventListener("submit", savePlayer); }
async function savePlayer(event) { event.preventDefault(); const player=selectedPlayer(); const data=Object.fromEntries(new FormData(event.currentTarget)); const attributes={}; for(const key of state.overview.attributeNames){attributes[key]=Number(data[`attr.${key}`]); delete data[`attr.${key}`];} data.attributes=attributes; data.heightCm=Number(data.heightCm); const status=$("#player-save-status"); status.textContent="保存中…"; try { const value=await api(`/api/admin/player-library/players/${encodeURIComponent(player.id)}`,{method:"POST",body:data}); state.players[state.players.findIndex((item)=>item.id===player.id)]=value.player; status.textContent=`已保存，总评 ${value.player.overall}`; await refreshOverview(); } catch(error){status.textContent=error.message;} }

function bindStudio() { const player=selectedPlayer(); if(!player)return; $$('[data-position]').forEach((input)=>input.oninput=()=>{const key=input.dataset.position; $(`[data-position-value="${key}"]`).textContent=`${Number(input.value).toFixed(1)}%`; $("#card-preview").style.setProperty(`--profile-${key}`,`${input.value}%`);}); $("#reset-position").onclick=()=>{const defaults={x:50,y:52,width:200}; $$('[data-position]').forEach((input)=>{input.value=defaults[input.dataset.position];input.dispatchEvent(new Event("input"));});}; $("#profile-file").onchange=async(event)=>{const file=event.target.files[0];if(!file)return;state.studioFile=file;$("#upload-label").textContent=file.name;const url=URL.createObjectURL(file);const preview=$("#card-preview");let image=$("#card-image");if(!image){image=document.createElement("img");image.id="card-image";image.className="s4-player-card-profile";image.dataset.playerCardArt="";preview.querySelector("[data-player-card-art-placeholder]")?.remove();preview.insertBefore(image,preview.firstChild);preview.classList.add("has-player-profile");}image.src=url;}; $("#save-profile").onclick=saveProfile; }
async function fileToWebp(file) { const bitmap=await createImageBitmap(file); const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)); const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise((resolve)=>canvas.toBlob(resolve,"image/webp",.9));return await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(blob);}); }
async function saveProfile(){const player=selectedPlayer();const button=$("#save-profile");button.disabled=true;button.textContent="处理中…";try{const body=Object.fromEntries($$('[data-position]').map((input)=>[input.dataset.position,Number(input.value)]));if(state.studioFile){body.imageDataUrl=await fileToWebp(state.studioFile);body.sourceFileName=state.studioFile.name;}const value=await api(`/api/admin/player-library/profiles/${encodeURIComponent(player.id)}`,{method:"POST",body});player.profile=value.profile;state.studioFile=null;toast("卡画与定位已保存");renderStudio();await refreshOverview();}catch(error){toast(error.message,true);button.disabled=false;button.textContent="保存卡画与定位";}}

function openModal(title, body, actions="") { const modal=$("#modal");modal.innerHTML=`<section class="dialog"><header><h2>${title}</h2><button data-close>×</button></header><div class="dialog-body">${body}<div class="dialog-actions">${actions}</div></div></section>`;modal.hidden=false;$('[data-close]',modal).onclick=()=>modal.hidden=true; }
function openDraftDialog(){const attrs=Object.fromEntries(state.overview.attributeNames.map((key)=>[key,70]));openModal("制作新球员卡",`<form id="draft-form"><div class="form-grid">${inputField("name","球员姓名","")}${inputField("sourceName","英文/来源名","")}${inputField("grade","评级","C",state.overview.grades)}${inputField("role","主位置","ST",state.overview.roles)}${inputField("nationality","国籍","")}${inputField("club","俱乐部","")}${inputField("heightCm","身高 cm",180)}${inputField("preferredFoot","惯用脚","right",[{value:"right",label:"右脚"},{value:"left",label:"左脚"},{value:"both",label:"双足"}])}</div><p>新卡先进入暂存池；26 项属性初始为 70，可在球员库中继续精调。</p></form>`,`<button data-close2>取消</button><button class="primary" id="create-draft">创建暂存卡</button>`);$('[data-close2]').onclick=()=>$("#modal").hidden=true;$("#create-draft").onclick=async()=>{try{const body=Object.fromEntries(new FormData($("#draft-form")));body.heightCm=Number(body.heightCm);body.attributes=attrs;const value=await api("/api/admin/player-library/drafts",{method:"POST",body});state.players.push(value.players[0]);state.selectedId=value.players[0].id;$("#modal").hidden=true;toast("新卡已进入暂存池");await refreshOverview();render();}catch(error){toast(error.message,true);}};}
function openBatchDialog(){const sample=JSON.stringify([{name:"示例球员",sourceName:"Example Player",grade:"C",role:"ST",nationality:"中国",club:"黄狗竞技",heightCm:180,preferredFoot:"right",attributes:Object.fromEntries(state.overview.attributeNames.map((key)=>[key,70]))}],null,2);openModal("批量制卡",`<form id="batch-form"><div class="form-grid"><label class="wide">批次名称<input name="name" required></label><label class="wide">批次说明<input name="description"></label></div><label style="margin-top:14px">球员 JSON 数组<textarea name="rows">${escapeHtml(sample)}</textarea></label></form>`,`<button data-close2>取消</button><button class="primary" id="create-batch">创建批次与暂存卡</button>`);$('[data-close2]').onclick=()=>$("#modal").hidden=true;$("#create-batch").onclick=async()=>{try{const data=Object.fromEntries(new FormData($("#batch-form")));const rows=JSON.parse(data.rows);const batch=await api("/api/admin/player-library/batches",{method:"POST",body:{name:data.name,description:data.description}});const value=await api("/api/admin/player-library/drafts",{method:"POST",body:{rows,batchId:batch.batch.id}});state.players.push(...value.players);$("#modal").hidden=true;toast(`已创建 ${value.players.length} 张暂存卡`);await refreshOverview();render();}catch(error){toast(error.message,true);}};}
async function publishSelected(){try{const value=await api("/api/admin/player-library/publish",{method:"POST",body:{ids:[...state.selectedPublish]}});for(const published of value.players){const index=state.players.findIndex((player)=>player.id===published.id);state.players[index]=published;}state.selectedPublish.clear();toast(`已上线 ${value.players.length} 名球员`);await refreshOverview();renderStudio();}catch(error){toast(error.message,true);}}
async function refreshOverview(){state.overview=await api("/api/admin/player-library");}

function issueList(title, items, mapper=(item)=>String(item)){return `<section class="panel"><header class="panel-head"><h3>${title}</h3><small>${items.length} 项</small></header><div class="audit-list">${items.map((item)=>`<article><b>${escapeHtml(mapper(item))}</b></article>`).join("")||'<p class="empty">无异常</p>'}</div></section>`;}
function renderAudit(){const a=state.overview.audit;$("#app").innerHTML=`${pageHead("DATA INTEGRITY","球员与卡画审计","直接检查生产目录、基础目录、注册表和本地卡画文件。",'<button id="refresh-audit">重新审计</button>')}${kpisMarkup()}<section class="audit-grid">${distributionMarkup("评级分布",a.grade)}${distributionMarkup("位置分布",a.role)}${distributionMarkup("卡画来源",a.sourceGroup)}${issueList("缺失卡画文件",a.missingAssets,(item)=>`${item.id} · ${item.fileName}`)}${issueList("孤立卡画注册",a.orphanProfiles)}${issueList("目录总评不一致",a.overallMismatchPlayers)}${issueList("重复球员 ID",a.duplicateIds,(item)=>`${item.label} × ${item.count}`)}${issueList("同名球员（人工复核）",a.duplicateNames,(item)=>`${item.label} × ${item.count}`)}</section>`;$("#refresh-audit").onclick=async()=>{await refreshOverview();renderAudit();toast("审计已刷新");};}
function selectedPackAccount(){return state.packManagement?.players.find((player)=>player.id===state.selectedAccountId)??null;}
function packAccountRows(query=""){const keyword=String(query).trim().toLowerCase();const players=(state.packManagement?.players??[]).filter((player)=>!keyword||`${player.nickname} ${player.id} ${player.teamName}`.toLowerCase().includes(keyword));return players.map((player)=>`<button type="button" class="pack-account-row ${!state.grantAllPlayers&&player.id===state.selectedAccountId?"active":""}" data-pack-account="${escapeHtml(player.id)}"><span><strong>${escapeHtml(player.nickname)}</strong><small>${escapeHtml(player.teamName)} · ${escapeHtml(player.id)}</small></span><b>${player.totalPacks} 包</b></button>`).join("")||'<p class="empty">没有匹配的服务器玩家</p>';}
function bindPackAccountRows(){$("#pack-account-all")?.addEventListener("click",()=>{state.grantAllPlayers=true;renderPlayerPackManagement();});$$('[data-pack-account]').forEach((button)=>button.onclick=()=>{state.grantAllPlayers=false;state.selectedAccountId=button.dataset.packAccount;renderPlayerPackManagement();});}
function renderPlayerPackManagement(){
  const management=state.packManagement;
  if(!management){$("#app").innerHTML='<div class="loading">正在读取玩家卡包数据…</div>';return;}
  const selected=selectedPackAccount();
  const allPlayers=state.grantAllPlayers&&management.players.length>0;
  const balances=allPlayers?[`<article class="pack-balance-card"><small>接收玩家</small><b>${management.players.length}</b><span>全部注册账户</span></article>`,`<article class="pack-balance-card"><small>现有卡包</small><b>${management.players.reduce((sum,player)=>sum+player.totalPacks,0)}</b><span>全服当前库存</span></article>`].join(""):selected?.packs.map((pack)=>`<article class="pack-balance-card"><small>${escapeHtml(pack.name)}</small><b>${pack.count}</b><span>当前库存</span></article>`).join("")??"";
  const target=allPlayers?`<div class="pack-selected-player batch"><small>当前发放对象</small><h2>所有玩家</h2><p>当前服务器全部 ${management.players.length} 个注册账户</p><span>批量发放 · 每名玩家获得相同数量</span></div>`:selected?`<div class="pack-selected-player"><small>当前发放对象</small><h2>${escapeHtml(selected.nickname)}</h2><p>${escapeHtml(selected.teamName)} · ${escapeHtml(selected.id)}</p><span>${selected.setupComplete?"已完成建队":"尚未完成建队"}</span></div>`:"";
  const canGrant=allPlayers||selected;
  const form=canGrant?`<form id="pack-grant-form" class="pack-grant-form"><input type="hidden" name="scope" value="${allPlayers?"all":"player"}">${allPlayers?"":`<input type="hidden" name="accountId" value="${escapeHtml(selected.id)}">`}${target}<div class="pack-balance-grid">${balances}</div><label>卡包类型<select name="packType" required>${management.packTypes.map((pack)=>`<option value="${escapeHtml(pack.type)}">${escapeHtml(pack.name)}</option>`).join("")}</select></label><label>${allPlayers?"每名玩家发放数量":"发放数量"}<input name="count" type="number" min="1" max="${management.maxGrantCount}" step="1" value="1" required></label><label>发放原因<input name="reason" maxlength="120" value="后台运营发放" required></label><output id="pack-grant-status"></output><button id="pack-grant-submit" class="primary" type="submit">${allPlayers?"确认向所有玩家发放":"确认发放卡包"}</button></form>`:'<div class="empty">服务器中还没有可发放的玩家账户</div>';
  const allTarget=`<div class="pack-all-target"><button type="button" id="pack-account-all" class="pack-account-row all-players ${allPlayers?"active":""}"><span><strong>所有玩家</strong><small>向当前全部注册账户统一发放</small></span><b>${management.players.length} 人</b></button></div>`;
  $("#app").innerHTML=`${pageHead("PLAYER OPERATIONS","卡包发放","向指定玩家或所有玩家发放球员卡包；每次操作都会写入管理员审计记录。")}<section class="pack-admin-layout"><aside class="panel"><header class="panel-head"><div><h2>服务器玩家</h2><small>${management.players.length} 个账户</small></div></header>${allTarget}<div class="pack-account-filter"><input id="pack-account-search" placeholder="搜索昵称、球队或玩家 ID"></div><div class="pack-account-list" id="pack-account-list">${packAccountRows()}</div></aside><section class="panel pack-grant-panel">${form}</section></section>`;
  const search=$("#pack-account-search");if(search)search.oninput=()=>{$("#pack-account-list").innerHTML=packAccountRows(search.value);bindPackAccountRows();};
  bindPackAccountRows();$("#pack-grant-form")?.addEventListener("submit",grantPlayerPacks);
}
async function grantPlayerPacks(event){event.preventDefault();const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));data.count=Number(data.count);const allPlayers=data.scope==="all";const player=selectedPackAccount();const pack=state.packManagement.packTypes.find((item)=>item.type===data.packType);if((!allPlayers&&!player)||!pack)return;const recipientCount=state.packManagement.players.length;const confirmation=allPlayers?`确认向所有 ${recipientCount} 名玩家每人发放 ${data.count} 个${pack.name}？总计 ${recipientCount*data.count} 个卡包。`:`确认向 ${player.nickname} 发放 ${data.count} 个${pack.name}？`;if(!window.confirm(confirmation))return;const button=$("#pack-grant-submit");const status=$("#pack-grant-status");button.disabled=true;button.textContent="正在发放…";status.textContent=allPlayers?"正在批量写入所有玩家背包…":"正在写入玩家背包…";try{const value=await api("/api/admin/player-packs",{method:"POST",body:data});state.packManagement=await api("/api/admin/player-packs");state.audit=(await api("/api/admin/audit?limit=100")).entries;toast(allPlayers?`已向 ${value.recipientCount} 名玩家每人发放 ${value.grant.count} 个${value.grant.name}`:`已向 ${value.player.nickname} 发放 ${value.grant.count} 个${value.grant.name}`);renderPlayerPackManagement();}catch(error){status.textContent=error.message||"卡包发放失败";button.disabled=false;button.textContent=allPlayers?"确认向所有玩家发放":"确认发放卡包";}}
function renderOperations(){const audits=state.audit.map((entry)=>`<article><b>${escapeHtml(entry.action)}</b><small>${escapeHtml(entry.username)} · ${new Date(entry.createdAt).toLocaleString()} · ${escapeHtml(entry.adminActionId)}</small></article>`).join("");const tasks=state.tasks.map((task)=>`<article><b>${escapeHtml(task.type)} · ${escapeHtml(task.status)}</b><small>${escapeHtml(task.id)} · ${new Date(task.createdAt).toLocaleString()}</small></article>`).join("");$("#app").innerHTML=`${pageHead("SYSTEM FOUNDATION","任务与操作记录","保留现有 RBAC、幂等任务和管理员审计能力。")}<section class="audit-grid"><section class="panel"><header class="panel-head"><h2>系统任务</h2></header><div class="audit-list">${tasks||'<p class="empty">暂无任务</p>'}</div></section><section class="panel"><header class="panel-head"><h2>最近操作</h2></header><div class="audit-list">${audits||'<p class="empty">暂无记录</p>'}</div></section></section>`;}
function render(){if(!state.overview)return;$$('.nav').forEach((button)=>button.classList.toggle("active",button.dataset.page===state.page));if(state.page==="players")renderPlayers();else if(state.page==="studio")renderStudio();else if(state.page==="packs")renderPlayerPackManagement();else if(state.page==="audit")renderAudit();else renderOperations();}

$("#login-form").addEventListener("submit",login);$("#logout").onclick=logout;$$('.nav').forEach((button)=>button.onclick=()=>{state.page=button.dataset.page;render();});
import("./client/player-card/player-card.js").then((module)=>{playerCardMarkup=module.playerCardMarkup;if(state.page==="studio"&&state.overview)renderStudio();}).catch((error)=>{console.error("球员卡组件加载失败，后台登录与基础管理仍可使用",error);});
if(state.token)api("/api/admin/me").then(async(value)=>{state.profile=value.profile;showAdmin();await loadAll();}).catch(()=>{state.token="";localStorage.removeItem("ydl-admin-token");});
