let token = localStorage.getItem("ydl-admin-token") || "";
const $ = (s) => document.querySelector(s);
async function api(path, options = {}) { const response = await fetch(path, { ...options, headers: { "content-type": "application/json", ...(token ? { authorization: `Bearer ${token}` } : {}), ...(options.headers || {}) }, body: options.body && JSON.stringify(options.body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "请求失败"); return data; }
function showDashboard(profile) { $("#login").hidden = true; $("#dashboard").hidden = false; $("#role").textContent = `${profile.username} · ${profile.role}`; refresh(); }
async function refresh() { const [tasks, audit] = await Promise.all([api("/api/admin/tasks"), api("/api/admin/audit")]); $("#tasks").innerHTML = tasks.tasks.map((t) => `<li><b>${t.type}</b> · ${t.status} · <code>${t.id}</code></li>`).join("") || "<li>暂无任务</li>"; $("#audit").innerHTML = audit.entries.map((e) => `<li>${e.action} · ${new Date(e.createdAt).toLocaleString()}</li>`).join("") || "<li>暂无记录</li>"; }
$("#login-form").addEventListener("submit", async (event) => { event.preventDefault(); const errorBox = $("#login-error"); errorBox.textContent = ""; try { const data = await api("/api/admin/login", { method: "POST", body: Object.fromEntries(new FormData(event.currentTarget)) }); token = data.token; localStorage.setItem("ydl-admin-token", token); showDashboard(data.profile); } catch (error) { errorBox.textContent = error.message; } });
$("#task-form").addEventListener("submit", async (event) => { event.preventDefault(); try { const form = Object.fromEntries(new FormData(event.currentTarget)); form.payload = form.payload ? JSON.parse(form.payload) : {}; await api("/api/admin/tasks", { method: "POST", body: form }); $("#notice").textContent = "任务已创建"; refresh(); } catch (error) { $("#notice").textContent = error.message; } });
$("#gold-form").addEventListener("submit", async (event) => { event.preventDefault(); try { await api("/api/admin/players/gold", { method: "POST", body: Object.fromEntries(new FormData(event.currentTarget)) }); $("#notice").textContent = "金币调整已记录"; refresh(); } catch (error) { $("#notice").textContent = error.message; } });
if (token) api("/api/admin/me").then((data) => showDashboard(data.profile)).catch(() => { token = ""; localStorage.removeItem("ydl-admin-token"); });
