import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {navigateUntilInteractive} from '../navigation.mjs';
function fixture(){const window=new EventEmitter(),contents=new EventEmitter();window.webContents=contents;contents.getURL=()=>contents.url??'about:blank';contents.loadURL=url=>{contents.url=url;return new Promise((resolve,reject)=>{contents.loaded=resolve;contents.failed=reject;});};return {window,contents};}
test('interactive page opens without waiting for slow optional resources',async()=>{const f=fixture();const result=navigateUntilInteractive(f.window,'https://example.test/game');f.contents.emit('dom-ready');await result;assert.equal(f.contents.listenerCount('dom-ready'),0);f.contents.failed(Error('late subresource failure'));await new Promise(r=>setImmediate(r));});
test('total navigation timeout releases listeners and permits a clean retry',async()=>{const f=fixture();await assert.rejects(navigateUntilInteractive(f.window,'https://example.test/game',{timeoutMs:20}),/30 秒/);assert.equal(f.contents.listenerCount('did-fail-load'),0);const next=navigateUntilInteractive(f.window,'https://example.test/game');f.contents.emit('dom-ready');await next;});
test('cancellation and closed windows end the current attempt',async()=>{for(const kind of ['cancel','close','crash']){const f=fixture(),controller=new AbortController();const result=navigateUntilInteractive(f.window,'https://example.test/game',{signal:controller.signal});if(kind==='cancel')controller.abort(Error('cancelled'));if(kind==='close')f.window.emit('closed');if(kind==='crash')f.contents.emit('render-process-gone');await assert.rejects(result);assert.equal(f.contents.listenerCount('dom-ready'),0);}});
test('only main-frame errors fail navigation; another-origin DOM cannot mark it ready',async()=>{const f=fixture();const result=navigateUntilInteractive(f.window,'https://example.test/game');f.contents.url='about:blank';f.contents.emit('dom-ready');f.contents.emit('did-fail-load',{},-2,'image error','',false);assert.equal(f.contents.listenerCount('dom-ready'),1);f.contents.emit('did-fail-load',{},-105,'DNS error','',true);await assert.rejects(result,/DNS error/);});
