export const CAMPAIGN_REGULATION_CHAINS = 180;
export const CAMPAIGN_EXTRA_TIME_CHAINS = 60;
export const CAMPAIGN_REGULATION_LIVE_MS = 120_000;
export const CAMPAIGN_EXTRA_TIME_LIVE_MS = 40_000;
export const CHALLENGE_SECOND_LEG_COOLDOWN_MS = 180_000;

export const CHALLENGE_FIRST_LEG_MS = CAMPAIGN_REGULATION_LIVE_MS;
export const CHALLENGE_SECOND_LEG_MS = CAMPAIGN_REGULATION_LIVE_MS + CAMPAIGN_EXTRA_TIME_LIVE_MS;
export const CHALLENGE_TOTAL_DURATION_MS = CHALLENGE_FIRST_LEG_MS + CHALLENGE_SECOND_LEG_COOLDOWN_MS + CHALLENGE_SECOND_LEG_MS;

export const CHALLENGE_CONFIG = Object.freeze({
  regulationChains: CAMPAIGN_REGULATION_CHAINS,
  extraTimeChains: CAMPAIGN_EXTRA_TIME_CHAINS,
  regulationLiveMs: CAMPAIGN_REGULATION_LIVE_MS,
  extraTimeLiveMs: CAMPAIGN_EXTRA_TIME_LIVE_MS,
  secondLegCooldownMs: CHALLENGE_SECOND_LEG_COOLDOWN_MS,
  totalDurationMs: CHALLENGE_TOTAL_DURATION_MS,
});
