// Generated by scripts/build-map-assets.mjs; rerun after changing a map source.
export const MAP_ASSET_HASHES = Object.freeze({
  "assets/data/campaign-countries.geojson": "c30a31846d1c094490b4e28576afa0850fddacbb610e4d7a672956485926a62d",
  "assets/data/europe-cities.json": "ecfe1927c30ba1ef79b0d52dd9d8176fa14c9194f08e14defd3026669c902afa",
  "assets/data/south-america-cities.json": "11964f249dcc8a6543189472b9322678b10464706524a955a69b572bab47bf24",
  "assets/data/europe-clubs.json": "92612f7b96ce767e6c3504d2c18c77a5c0d7c0fe9dba218eb0ffaeefeed467ab",
  "assets/data/campaign-territories.geojson": "e6937b6c4dafb0cb7b6e207d6f8026a412a4cdbde0d6e52bb4d63fac7ca8f46e",
  "assets/data/territory-index.json": "629a8d525480632138fbf705985b8108e9c6cb3630126d6edd27d4e9515875a1",
  "assets/data/campaign-boundaries.json": "2f26e8d413d3822dc4265e70de0182de2f0bfe3a8e5cedc47b4b6c6f98381d6b",
  "assets/data/campaign-coastlines.json": "895ad261f34c7c7376de6a7a6a926fd4df86ca4440836408c6abe2331f611706",
  "assets/data/territory-resources.json": "e890f0ae10fa2499f80be802675ef0d405b724685b0af7bbc3e9f2ed18b01c70",
  "shared/config/map-relief-regions.json": "1a83af2c6e032658dce94a42f8d4bb50ba5287a5e2a89024fd39d45716582dc1",
  "assets/data/map-nature.json": "d1ee28b2cdb05c34d5767492beffa84aed73e26291df6a40a5275b93b2cb5a97",
  "assets/data/map-environment.json": "c8c65f6d3aece544de86537871900dadc364af38f480720edcdf3d6af4573a2f",
  "assets/map-relief/relief-mesh/europe.json": "8070736ffd9a8419f7901bf3b314e3bd213bd5cbe65d2a8387351ca306e2ae81",
  "assets/map-relief/relief-mesh/europe.bin": "768470a0ae6845b6ae6dfce0dc48e560c6a20daa15d62198223246cc86b46cdc",
  "assets/map-relief/relief-mesh/south-america.json": "b26a90d700a7ced905323f684da05b20b43d88d26fa0855570415598d26c6409",
  "assets/map-relief/relief-mesh/south-america.bin": "82fca311735ef35b99c754ea0a2ded86498cc64f6b53b7c76b26fbeeb59c3d5a",
  "assets/map-relief/relief-mesh/svalbard.json": "eea9cdb1b784124f1fc5d9123979af417ad62e2844f4a500b5fd83778a844e3c",
  "assets/map-relief/relief-mesh/svalbard.bin": "e952a78c7efae7ffa8a2cbcab3653aeac0d830283b86acd8c7830301f59cf725"
});

export function mapAssetUrl(path) {
  const relative = path.replace(/^\.\//, '');
  const hash = MAP_ASSET_HASHES[relative];
  if (!hash) throw new Error('Unknown map asset: ' + path);
  return './' + relative + '?v=sha256-' + hash;
}
